# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dns_seed.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ns_seed.proto\"D\n\x13RegistrationRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x64\x64rMe\x18\x03 \x01(\t\"4\n\x14RegistrationResponse\x12\x1c\n\x14last_registered_node\x18\x01 \x01(\t2H\n\tRegistrar\x12;\n\x0cRegisterNode\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dns_seed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONREQUEST']._serialized_start=18
  _globals['_REGISTRATIONREQUEST']._serialized_end=86
  _globals['_REGISTRATIONRESPONSE']._serialized_start=88
  _globals['_REGISTRATIONRESPONSE']._serialized_end=140
  _globals['_REGISTRAR']._serialized_start=142
  _globals['_REGISTRAR']._serialized_end=214
# @@protoc_insertion_point(module_scope)
